name: CI/CD with ECR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v6
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4

    # Login to ECR (-p exposes password in logs)
    - name: Login to ECR
      run: |
        aws ecr get-login-password --region ap-southeast-1 \
        | docker login --username AWS --password-stdin \
        ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com

    - name: Build Docker image
      run: |
        docker build -t devops-api .

    - name: Tag image
      run: |
        docker tag devops-api:latest \
        ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com/devops-api:latest

    - name: Push image
      run: |
        docker push \
        ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com/devops-api:latest

    - name: Setup SSH
      run: |
        echo "${{ secrets.EC2_KEY }}" > key.pem
        chmod 400 key.pem
    
    - name: terraform init
      run: terraform -chdir=terraform init
    
    - name: terraform apply
      run: |
        terraform -chdir=terraform apply -auto-approve \
          -var="key_name=${{ secrets.KEY_NAME }}" \
          -var="ecr_uri=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com/devops-api"
    
    - name: get public ip
      id: ip
      run: |
        echo "ip=$(terraform -chdir=terraform output -raw public_ip)" >> $GITHUB_OUTPUT

    - name: Wait for app
      run: sleep 60
    
      # Test endpoint  
    - name: Test API
      run: |
        curl http://${{ steps.ip.outputs.ip }}:8000/health
    
      # Destroy infra
    - name: Terraform Destroy
      # even if previous steps is fail.
      if: always()
      run: |
        terraform -chdir=terraform destroy -auto-approve \
          -var="key_name=${{ secrets.KEY_NAME }}" \
          -var="ecr_uri=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com/devops-api"

      